// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK1V3cO5xAXsAGive9bfTiSFrLylB4SU4',
    appId: '1:1045397450464:web:a7ef0b1eb6f20729e56a85',
    messagingSenderId: '1045397450464',
    projectId: 'bnya-833b5',
    authDomain: 'bnya-833b5.firebaseapp.com',
    storageBucket: 'bnya-833b5.firebasestorage.app',
    measurementId: 'G-Q4BHWYJQL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK04r3EAvpjJuZSQLXJv3JfJXb571WY9U',
    appId: '1:1045397450464:android:f2bcd60c4ef55fbee56a85',
    messagingSenderId: '1045397450464',
    projectId: 'bnya-833b5',
    storageBucket: 'bnya-833b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6R3H-o4_8dN5cDH3AIq1GtQPDYR7qq4U',
    appId: '1:1045397450464:ios:a38b39e5a6f0eb9fe56a85',
    messagingSenderId: '1045397450464',
    projectId: 'bnya-833b5',
    storageBucket: 'bnya-833b5.firebasestorage.app',
    iosBundleId: 'com.example.bnya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6R3H-o4_8dN5cDH3AIq1GtQPDYR7qq4U',
    appId: '1:1045397450464:ios:a38b39e5a6f0eb9fe56a85',
    messagingSenderId: '1045397450464',
    projectId: 'bnya-833b5',
    storageBucket: 'bnya-833b5.firebasestorage.app',
    iosBundleId: 'com.example.bnya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK1V3cO5xAXsAGive9bfTiSFrLylB4SU4',
    appId: '1:1045397450464:web:83077489114ac593e56a85',
    messagingSenderId: '1045397450464',
    projectId: 'bnya-833b5',
    authDomain: 'bnya-833b5.firebaseapp.com',
    storageBucket: 'bnya-833b5.firebasestorage.app',
    measurementId: 'G-73J063MQ4B',
  );
}
